name: End to end tests

on:
  pull_request:
    branches: ['*']
  push:
    branches: [ master, develop ]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install project dependencies
        run: npm ci
      - name: Build project
        run: npm run build:prod
      - name: Run tests
        env:
          E2E_TEST: true
          NODE_ENV: development
          DEBUG: 'waggle*,zbay*,testcafe:*electron*'
        uses: DevExpress/testcafe-action@latest
        with:
            args: "--color --hostname localhost \"electron:.\" \"./**/*.e2e.js\""
